package fc.compiler.language.cobol;

import fc.compiler.common.ast.Expression;
import fc.compiler.common.ast.Statement;
import fc.compiler.common.ast.expression.Identifier;
import fc.compiler.common.ast.statement.*;
import fc.compiler.common.parser.StringTokenParserBase;
import fc.compiler.common.parser.StringTokenParserRegistry;
import fc.compiler.common.parser.StringTokenReader;
import fc.compiler.language.cobol.ast.CobolCompilationUnit;
import fc.compiler.language.cobol.ast.CobolProgram;
import fc.compiler.language.cobol.ast.clause.*;
import fc.compiler.language.cobol.ast.division.*;
import fc.compiler.language.cobol.ast.statement.*;

import java.util.ArrayList;
import java.util.List;

import static fc.compiler.common.token.StringTokenKind.*;
import static fc.compiler.language.cobol.CobolTokenKind.*;

public class CobolParserAutoGenerated extends StringTokenParserBase {
	public static StringTokenParserRegistry initRegistry() {
		StringTokenParserRegistry map = new StringTokenParserRegistry();
		map.put(IF, CobolParserAutoGenerated::parseIfStatement);
		map.put(null, CobolParserAutoGenerated::parseThenStatement);
		map.put(NEXT, CobolParserAutoGenerated::parseThenStatement);
		map.put(null, CobolParserAutoGenerated::parseElseStatement);
		map.put(NEXT, CobolParserAutoGenerated::parseElseStatement);
		map.put(EXIT, CobolParserAutoGenerated::parseExitStatement);
		map.put(STOP, CobolParserAutoGenerated::parseStopStatement);
		map.put(CONTINUE, CobolParserAutoGenerated::parseContinueStatement);
		return map;
	}
	public static CobolCompilationUnit parseCobolCompilationUnit(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKindAnyOf(ID, IDENTIFICATION)) return null;

		CobolCompilationUnit result = new CobolCompilationUnit();
		List<CobolProgram> cobolProgramList = parseCobolProgramList(reader, registry);
		result.cobolProgramList(cobolProgramList);
		return result;
	}
	public static CobolProgram parseCobolProgram(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKindAnyOf(ID, IDENTIFICATION)) return null;

		CobolProgram result = new CobolProgram();
		result.idDivision(parseIdDivision(reader, registry));
		result.environmentDivision(parseEnvironmentDivision(reader, registry));
		result.dataDivision(parseDataDivision(reader, registry));
		result.procedureDivision(parseProcedureDivision(reader, registry));
		List<CobolProgram> cobolProgramList = parseCobolProgramList(reader, registry);
		result.cobolProgramList(cobolProgramList);
		result.endProgram(parseEndProgram(reader, registry));
		return result;
	}
	public static Identifier parseEndProgram(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(END)) return null;
		reader.accept(END);
		reader.accept(PROGRAM);
		Identifier result = parseIdentifier(reader, registry);
		reader.accept(DOT);
		return result;
	}
	public static IdDivision parseIdDivision(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKindAnyOf(ID, IDENTIFICATION)) return null;

		IdDivision result = new IdDivision();
reader.acceptAnyOf(ID, IDENTIFICATION);
		reader.accept(DIVISION);
		reader.accept(DOT);
		result.programIdParagraph(parseProgramIdParagraph(reader, registry));
		List<IdDivisionOptionalParagraph> idDivisionOptionalParagraphList = parseIdDivisionOptionalParagraphList(reader, registry);
		result.idDivisionOptionalParagraphList(idDivisionOptionalParagraphList);
		return result;
	}
	public static Identifier parseProgramIdParagraph(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(PROGRAM_ID)) return null;
		reader.accept(PROGRAM_ID);
		reader.accept(DOT);
		Identifier result = parseIdentifier(reader, registry);
		reader.accept(DOT);
		return result;
	}
	public static IdDivisionOptionalParagraph parseIdDivisionOptionalParagraph(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKindAnyOf(DATE_WRITTEN, INSTALLATION, SECURITY, REMARKS, AUTHOR, DATE_COMPILED)) return null;

		IdDivisionOptionalParagraph result = new IdDivisionOptionalParagraph();
reader.acceptAnyOf(DATE_WRITTEN, INSTALLATION, SECURITY, REMARKS, AUTHOR, DATE_COMPILED);
		return result;
	}
	public static EnvironmentDivision parseEnvironmentDivision(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(ENVIRONMENT)) return null;

		EnvironmentDivision result = new EnvironmentDivision();
		reader.accept(ENVIRONMENT);
		reader.accept(DIVISION);
		reader.accept(DOT);
		result.configurationSection(parseConfigurationSection(reader, registry));
		result.inputOutputSection(parseInputOutputSection(reader, registry));
		return result;
	}
	public static ConfigurationSection parseConfigurationSection(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(CONFIGURATION)) return null;

		ConfigurationSection result = new ConfigurationSection();
		reader.accept(CONFIGURATION);
		reader.accept(SECTION);
		reader.accept(DOT);
		result.sourceComputerParagraph(parseSourceComputerParagraph(reader, registry));
		result.objectComputerParagraph(parseObjectComputerParagraph(reader, registry));
		return result;
	}
	public static Identifier parseSourceComputerParagraph(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(SOURCE_COMPUTER)) return null;
		reader.accept(SOURCE_COMPUTER);
		reader.accept(DOT);
		Identifier result = parseIdentifier(reader, registry);
		reader.optional(WITH);
		reader.optional(DEBUGGING);
		reader.optional(MODE);
		reader.accept(DOT);
		return result;
	}
	public static Identifier parseObjectComputerParagraph(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(OBJECT_COMPUTER)) return null;
		reader.accept(OBJECT_COMPUTER);
		reader.accept(DOT);
		Identifier result = parseIdentifier(reader, registry);
		reader.accept(DOT);
		return result;
	}
	public static InputOutputSection parseInputOutputSection(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(INPUT_OUTPUT)) return null;

		InputOutputSection result = new InputOutputSection();
		reader.accept(INPUT_OUTPUT);
		reader.accept(SECTION);
		reader.accept(DOT);
		result.fileControlParagraph(parseFileControlParagraph(reader, registry));
		result.ioControlParagraph(parseIoControlParagraph(reader, registry));
		return result;
	}
	public static FileControlParagraph parseFileControlParagraph(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(FILE_CONTROL)) return null;

		FileControlParagraph result = new FileControlParagraph();
		reader.accept(FILE_CONTROL);
		reader.accept(DOT);
		List<FileControlEntry> fileControlEntryList = parseFileControlEntryList(reader, registry);
		result.fileControlEntryList(fileControlEntryList);
		return result;
	}
	public static FileControlEntry parseFileControlEntry(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(SELECT)) return null;

		FileControlEntry result = new FileControlEntry();
		reader.accept(SELECT);
		reader.optional(OPTIONAL);
		result.fileName(parseIdentifier(reader, registry));
reader.acceptAnyOf(PASSWORD, RELATIVE);
		reader.accept(DOT);
		return result;
	}
	public static Identifier parsePasswordClause(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(PASSWORD)) return null;
		reader.accept(PASSWORD);
		reader.optional(IS);
		Identifier result = parseIdentifier(reader, registry);
		return result;
	}
	public static Identifier parseRelativeKeyClause(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(RELATIVE)) return null;
		reader.accept(RELATIVE);
		reader.optional(KEY);
		reader.optional(IS);
		Identifier result = parseIdentifier(reader, registry);
		return result;
	}
	public static IoControlParagraph parseIoControlParagraph(StringTokenReader reader, StringTokenParserRegistry registry) {

		return null;
	}
	public static DataDivision parseDataDivision(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(DATA)) return null;

		DataDivision result = new DataDivision();
		reader.accept(DATA);
		reader.accept(DIVISION);
		reader.accept(DOT);
reader.acceptAnyOf(FILE, LINKAGE, WORKING_STORAGE);
		return result;
	}
	public static WorkingStorageSection parseWorkingStorageSection(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(WORKING_STORAGE)) return null;

		WorkingStorageSection result = new WorkingStorageSection();
		reader.accept(WORKING_STORAGE);
		reader.accept(SECTION);
		reader.accept(DOT);
		List<DataDescriptionEntry> dataDescriptionEntryList = parseDataDescriptionEntryList(reader, registry);
		result.dataDescriptionEntryList(dataDescriptionEntryList);
		return result;
	}
	public static LinkageSection parseLinkageSection(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(LINKAGE)) return null;

		LinkageSection result = new LinkageSection();
		reader.accept(LINKAGE);
		reader.accept(SECTION);
		reader.accept(DOT);
		List<DataDescriptionEntry> dataDescriptionEntryList = parseDataDescriptionEntryList(reader, registry);
		result.dataDescriptionEntryList(dataDescriptionEntryList);
		return result;
	}
	public static FileSection parseFileSection(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(FILE)) return null;

		FileSection result = new FileSection();
		reader.accept(FILE);
		reader.accept(SECTION);
		reader.accept(DOT);
		return result;
	}
	public static DataDescriptionEntry parseDataDescriptionEntry(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(DOT)) return null;

		DataDescriptionEntry result = new DataDescriptionEntry();
		result.dataName(parseIdentifier(reader, registry));
		result.dummy1(parseIdentifier(reader, registry));
		result.dummy2(parseIdentifier(reader, registry));
		reader.accept(DOT);
		return result;
	}
	public static Identifier parseDataPictureClause(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKindAnyOf(PICTURE, PIC)) return null;
reader.acceptAnyOf(PICTURE, PIC);
		reader.optional(IS);
		Identifier result = parseIdentifier(reader, registry);
		return result;
	}
	public static Identifier parseDataValueClause(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKindAnyOf(VALUES, VALUE)) return null;
reader.optionalAnyOf(VALUES, VALUE);
		Identifier result = parseIdentifier(reader, registry);
		return result;
	}
	public static ProcedureDivision parseProcedureDivision(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(PROCEDURE)) return null;

		ProcedureDivision result = new ProcedureDivision();
		reader.accept(PROCEDURE);
		reader.accept(DIVISION);
		result.procedureUsingClause(parseProcedureUsingClause(reader, registry));
		result.procedureGivingClause(parseProcedureGivingClause(reader, registry));
		reader.accept(DOT);
		result.procedureDeclaratives(parseIdentifier(reader, registry));
		List<Statement> statementList = parseStatementList(reader, registry);
		result.statementList(statementList);
		return result;
	}
	public static Identifier parseProcedureGivingClause(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKindAnyOf(GIVING, RETURNING)) return null;
reader.acceptAnyOf(GIVING, RETURNING);
		Identifier result = parseIdentifier(reader, registry);
		return result;
	}
	public static ProcedureUsingClause parseProcedureUsingClause(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(USING)) return null;

		ProcedureUsingClause result = new ProcedureUsingClause();
		reader.accept(USING);
		List<Expression> procedureParameterList = parseExpressionList(reader, registry);
		result.procedureParameterList(procedureParameterList);
		return result;
	}
	public static IfStatement parseIfStatement(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(IF)) return null;

		IfStatement result = new IfStatement();
		reader.accept(IF);
		result.condition(parseIdentifier(reader, registry));
		reader.optional(THEN);
		result.thenStatement(parseThenStatement(reader, registry));
		reader.optional(ELSE);
		result.elseStatement(parseElseStatement(reader, registry));
		reader.optional(END_IF);
		return result;
	}
	public static ThenStatement parseThenStatement(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKindAnyOf(null, NEXT)) return null;

		ThenStatement result = new ThenStatement();
if (reader.acceptAnyOf(NEXT)) {
} else {		List<Statement> statementList = parseStatementList(reader, registry);
		result.statementList(statementList);
}		return result;
	}
	public static ElseStatement parseElseStatement(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKindAnyOf(null, NEXT)) return null;

		ElseStatement result = new ElseStatement();
if (reader.acceptAnyOf(NEXT)) {
} else {		List<Statement> statementList = parseStatementList(reader, registry);
		result.statementList(statementList);
}		return result;
	}
	public static ExitStatement parseExitStatement(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(EXIT)) return null;

		ExitStatement result = new ExitStatement();
		reader.accept(EXIT);
		reader.optional(PROGRAM);
		return result;
	}
	public static StopStatement parseStopStatement(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(STOP)) return null;

		StopStatement result = new StopStatement();
		reader.accept(STOP);
reader.acceptAnyOf();
		return result;
	}
	public static ContinueStatement parseContinueStatement(StringTokenReader reader, StringTokenParserRegistry registry) {
		if (!reader.isKind(CONTINUE)) return null;

		ContinueStatement result = new ContinueStatement();
		reader.accept(CONTINUE);
		return result;
	}
public static List<CobolProgram> parseCobolProgramList(StringTokenReader reader, StringTokenParserRegistry registry) {
	List<CobolProgram> list = new ArrayList<>();
	while (true) {
		CobolProgram o = parseCobolProgram(reader, registry);
		if (o == null) break;
		list.add(o);
	};
	return list;
}

public static List<IdDivisionOptionalParagraph> parseIdDivisionOptionalParagraphList(StringTokenReader reader, StringTokenParserRegistry registry) {
	List<IdDivisionOptionalParagraph> list = new ArrayList<>();
	while (true) {
		IdDivisionOptionalParagraph o = parseIdDivisionOptionalParagraph(reader, registry);
		if (o == null) break;
		list.add(o);
	};
	return list;
}

public static List<FileControlEntry> parseFileControlEntryList(StringTokenReader reader, StringTokenParserRegistry registry) {
	List<FileControlEntry> list = new ArrayList<>();
	while (true) {
		FileControlEntry o = parseFileControlEntry(reader, registry);
		if (o == null) break;
		list.add(o);
	};
	return list;
}

public static List<DataDescriptionEntry> parseDataDescriptionEntryList(StringTokenReader reader, StringTokenParserRegistry registry) {
	List<DataDescriptionEntry> list = new ArrayList<>();
	while (true) {
		DataDescriptionEntry o = parseDataDescriptionEntry(reader, registry);
		if (o == null) break;
		list.add(o);
	};
	return list;
}

public static List<Statement> parseStatementList(StringTokenReader reader, StringTokenParserRegistry registry) {
	List<Statement> list = new ArrayList<>();
	while (true) {
		Statement o = parseStatement(reader, registry);
		if (o == null) break;
		list.add(o);
	};
	return list;
}

public static List<Expression> parseExpressionList(StringTokenReader reader, StringTokenParserRegistry registry) {
	List<Expression> list = new ArrayList<>();
	while (true) {
		Expression o = parseExpression(reader, registry);
		if (o == null) break;
		list.add(o);
	};
	return list;
}

}
