package fc.compiler.language.antlr;

import fc.compiler.language.antlr.ast.AntlrCompilationUnit;
import fc.compiler.language.antlr.modern.CodeGenerator;
import fc.compiler.language.antlr.modern.IdentifiableTokenFinder;
import fc.compiler.language.antlr.modern.RuleFeatureAnalyzer;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import static fc.compiler.language.antlr.AntlrParserTest.*;

/**
 * @author FC
 */
class AntlrVisitorTest {
	@Test
	public void visitCompilationUnit() throws IOException {
		AntlrCompilationUnit unit = parseFile("d:\\cosmos\\resources\\cst\\languages\\cobol\\cobol85_fc.g4");
//		AntlrCompilationUnit unit = parse("grammar Cobol85;\n" +
//				"statement:ifStatement | exitStatement;\n" +
//				"ifStatement : IF condition THEN? thenStatement; \n" +
//				"thenStatement : NEXT SENTENCE | statement* ;\n" +
//				"exitStatement : EXIT PROGRAM?  ;"
//		);
		RuleFeatureAnalyzer featureAnalyzer = new RuleFeatureAnalyzer();
		featureAnalyzer.visit(unit, null);
		IdentifiableTokenFinder finder = new IdentifiableTokenFinder();
		finder.visit(unit, null);
		CodeGenerator visitor = new CodeGenerator()
				.finder(finder)
				.featureAnalyzer(featureAnalyzer);
		visitor.visit(unit, null);
//		unit.accept(visitor, null);
		Files.writeString(Paths.get("D:\\cosmos\\code\\fc_code\\java\\fc_compiler\\core\\src\\main\\java\\fc\\compiler\\language\\cobol\\CobolParserAutoGenerated.java"),
				visitor.toString());
	}
}