package fc.compiler.language.antlr.modern;

import fc.compiler.common.ast.Expression;
import fc.compiler.common.ast.expression.Identifier;
import fc.compiler.common.ast.expression.Literal;
import fc.compiler.common.util.StrUtils;
import fc.compiler.language.antlr.ast.*;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.apache.commons.lang3.StringUtils;

import java.util.*;
import java.util.stream.Collectors;

import static fc.compiler.language.antlr.modern.AntlrVisitor.*;
import static java.lang.StringTemplate.STR;

/**
 * @author FC
 */
@Accessors(fluent = true)
public class CodeGenerator extends AntlrVisitorBase<Object> {
	public static final String PARAMETERS_READER_REGISTRY = "(TokenReader reader, ParserRegistry registry) {";
	public static final String ARGUMENTS_READER_REGISTRY = "(reader, registry)";

	@Setter IdentifiableTokenFinder finder;
	@Setter	RuleFeatureAnalyzer featureAnalyzer;
	List<String> statementParsers = new ArrayList<>();
	List<String> expressionParsers = new ArrayList<>();

	StringBuilder sbParser = new StringBuilder();
	StringBuilder sbLexer = new StringBuilder();

	String lexerClassName = "";
	String parserClassName = "CobolParserAutoGenerated";
	String indent  = "\t";
	String indent2 = "\t\t";
	String indent3 = "\t\t\t";
	String indent4 = "\t\t\t\t";
	String lineSeparator = System.lineSeparator();
	Map<String, String> methods = new LinkedHashMap<>();

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(HEADER).append(lineSeparator);
		sb.append(STR."public class \{parserClassName} extends ParserBase {").append(lineSeparator);
		sb.append(buildParserRegistry());
		sb.append(sbParser.toString());
		for (String method : methods.values()) {
			sb.append(method).append(lineSeparator);
		}
		sb.append("}").append(lineSeparator);
		return sb.toString();
	}

	private String buildParserRegistry() {
		StringBuilder sb = new StringBuilder();
		sb.append(indent).append("public static ParserRegistry initRegistry() {").append(lineSeparator);
		sb.append(indent2).append("ParserRegistry map = new ParserRegistry();").append(lineSeparator);
		for (String parserRegistration : statementParsers) {
			sb.append(indent2).append(parserRegistration).append(lineSeparator);
		}
		sb.append(indent2).append("return map;").append(lineSeparator);
		sb.append(indent).append("}").append(lineSeparator);
		return sb.toString();
	}

	public Void visit(Rule rule, Object p) {
		String ruleName = rule.name().id();
		String returnType = StringUtils.capitalize(ruleName);
		List<IdentifiableToken> tokenList = getIdentifiableTokenList(ruleName);
		// ignore it because ParserBase already has it.
		if ("statement".equalsIgnoreCase(ruleName)) {
//			rule.expression()
			return null;
		}

		String quickTest = buildQuickTestForRule(tokenList);

		RuleFeatureAnalyzer.RuleFeature feature = featureAnalyzer.mapRule2Feature.get(ruleName);
		boolean enableOptimization = !ruleName.endsWith("Statement") && !ruleName.endsWith("Expression");
		if (enableOptimization
				&& rule.expression() instanceof Sequence sequence
				&& !feature.hasMultipleToReturn()) {
			buildMethod(sequence, p, ruleName, quickTest);
			return null;
		}
//		if (rule.expression() instanceof Sequence sequence
//				&& hasOnlyOneRuleInSequence(sequence)) {
//			buildInlineSequence(sequence, p, ruleName);
//			return null;
//		}

		sbParser.append(indent).append(STR."public static \{returnType} parse\{returnType}\{PARAMETERS_READER_REGISTRY}\n");
		if (quickTest != null && !quickTest.isEmpty())
			sbParser.append(indent2).append(STR."if (!\{quickTest}) return null;\n");
		sbParser.append("\n");
		if (rule.expression() == null) {    // blank. e.g. ruleA: ;
			sbParser.append(indent2).append("return null;").append(lineSeparator);
		} else {
			sbParser.append(indent2).append(STR."\{returnType} result = new \{returnType}();\n");
			rule.expression().accept(this, p);
			sbParser.append(indent2).append("return result;\n");
		}
		sbParser.append(indent).append("}\n");

		if (ruleName.endsWith("Statement")) {
			if (tokenList.size() == 1) {
				if (tokenList.get(0).alternatives() == null) {
					String tokenKind = tokenList.get(0).tokenKind();
					statementParsers.add(STR."map.put(\{tokenKind}, \{parserClassName}::parse\{returnType});");
				} else {
					for (String tokenKind : tokenList.get(0).alternatives()) {
						statementParsers.add(STR."map.put(\{tokenKind}, \{parserClassName}::parse\{returnType});");
					}
				}
			}
		}

		return null;
	}

	/**
	 * If a rule contains at most one Identifier, just return this Identifier
	 * to avoid creating a new ASTNode class.
	 */
	private void buildMethod(Sequence node, Object p, String ruleName, String quickTest) {
		sbParser.append(indent).append(String.format("public static Identifier parse%s%s",
				StringUtils.capitalize(ruleName), PARAMETERS_READER_REGISTRY)).append(lineSeparator);
		if (quickTest != null && !quickTest.isEmpty())
			sbParser.append(indent2).append(STR."if (!\{quickTest}) return null;\n");

		for (Expression expr : node.children()) {
			if (expr instanceof Identifier id) {
				visit(id, p, true);
			} else {
				visit(expr, p);
			}
		}
		sbParser.append(indent2).append("return result;").append(lineSeparator);
		sbParser.append(indent).append("}").append(lineSeparator);
	}

	private String buildQuickTestForRule(List<IdentifiableToken> tokenList) {
		if (tokenList.size() == 1) {
			if (tokenList.get(0).alternatives() == null) {
				String tokenKind = tokenList.get(0).tokenKind();
				return STR."reader.isKind(\{tokenKind})";
			} else {
				String tokenKinds = tokenList.get(0).alternatives().toString();
				tokenKinds = tokenKinds.substring(1, tokenKinds.length()-1);
				return STR."reader.isKindAnyOf(\{tokenKinds})";
			}
		}
		return "";
	}

	private List<IdentifiableToken> getIdentifiableTokenList(String ruleName) {
		List<IdentifiableToken> tokenList = finder.rule2IdentifiableTokenList.get(ruleName);
		if (tokenList == null) {
			finder.visit(rules.get(ruleName), null);
			tokenList = finder.rule2IdentifiableTokenList.get(ruleName);
		}
		return tokenList;
	}

	public Void visit(Sequence node, Object p) {
		for (Expression expr : node.children()) {
			expr.accept(this, p);
		}
		return null;
	}

//	protected boolean hasOnlyOneRuleInSequence(Sequence sequence) {
//		int i = 0;
//		for (Expression expr : sequence.children()) {
//			Identifier id = asIdentifier(expr);
//			if (id != null) {
//				if (!isAllUpperCase(id.id())
//					&& !rules.containsKey(id.id())) {
//					i++;
//				}
//			} else if (expr instanceof Literal<?>){
//			} else {
//				return false;   // directly return false if neither identifier nor literal.
//			}
//		}
//		return i == 1;
//	}

	/**
	 * case only keywords/literal: idDivision : (IDENTIFICATION | ID) DIVISION '.'
	 * case nested rules:          statement: ifStatement | forStatement | returnStatement
	 * case keywords & multiple:   thenStatement : NEXT SENTENCE | statement*
	 */
	public Void visit(Alternatives node, Object p) {
		List<Expression> list = node.children().stream().filter(expr -> !isMultipleQuantified(expr)
								&& !isRuleOfAlternative(expr)).toList();
		String tokenKindList = buildIdentifiableTokenKindList(list);
		if (node.children().size() == list.size()) { // only keywords or literals
			String acceptOrOptional = isOptional(toQuantifiedType(p)) ? "optionalAnyOf" : "acceptAnyOf";
			sbParser.append(String.format("reader.%s(%s);", acceptOrOptional, tokenKindList)).append(lineSeparator);
		} else {
			List<Expression> multipleQuantifiedList = node.children().stream().filter(expr -> isMultipleQuantified(expr)).toList();
			List<Expression> subRuleIsAlternativeList = node.children().stream().filter(expr -> isRuleOfAlternative(expr)).toList();
			if (1 == multipleQuantifiedList.size() && 0 == subRuleIsAlternativeList.size()) {
				String acceptOrOptional = isOptional(toQuantifiedType(p)) ? "optionalAnyOf" : "acceptAnyOf";
				sbParser.append(String.format("if (reader.%s(%s)) {", acceptOrOptional, tokenKindList)).append(lineSeparator);
				sbParser.append("} else {");
				visit(multipleQuantifiedList.get(0), p);
				sbParser.append("}");
			} else if (1 == subRuleIsAlternativeList.size() && 0 == multipleQuantifiedList.size()) {
			} else {
				System.out.println("No implemented for " + node.toString());
				for (Expression expr: node.children()) {
					expr.accept(this, p);
				}
			}
		}

		return null;
	}

	private static boolean isMultipleQuantified(Expression expr) {
		return expr instanceof QuantifiedExpression qe && qe.isMultiple();
	}

	private boolean isRuleOfAlternative(Expression expr) {
		return expr instanceof Identifier id
				&& rules.containsKey(id.id())
				&& rules.get(id.id()).expression() instanceof Alternatives;
	}

	private String buildIdentifiableTokenKindList(List<Expression> expressions) {
		List<IdentifiableToken> tokenList = finder.getIdentifiableTokenList(expressions);
		if (tokenList.size() == 0) {
			return "";
		}
		return tokenList.get(0).alternatives.stream().collect(Collectors.joining(", "));
	}

	/**
	 * An identifier can be
	 * - a rule name defined in grammar file;
	 * - a token kind if all letters are uppercase like WHILE
	 * - a normal identifier.
	 */
	public Void visit(Identifier node, Object p) {
		visit(node, p, false);
		return null;
	}

	public Void visit(Identifier node, Object p, boolean returnIdentifier) {
		String code = null;
		String id = node.id();
		if (StrUtils.isAllUpperCase(id)) {
			String quantifiedType = toQuantifiedType(p);
			String acceptOrOptional = isOptional(quantifiedType) ? "optional" : "accept";
			code = String.format("reader.%s(%s);", acceptOrOptional, id);
		} else if (rules.containsKey(id)) {
			code = String.format("result.%s(parse%s(reader, registry));", id, StringUtils.capitalize(id));
		} else {
			if (returnIdentifier) {
				code = "Identifier result = parseIdentifier(reader, registry);";
			} else {
				code = String.format("result.%s(parseIdentifier(reader, registry));", id);
			}
		}
		sbParser.append(indent2).append(code).append(lineSeparator);
		return null;
	}

	public Void visit(Literal node, Object p) {
		String quantifiedType = toQuantifiedType(p);
		String key = String.valueOf(node.value());
		sbParser.append(indent2);
		if (mapStringLiteral2TokenKind.containsKey(key)) {
			String acceptOrOptional = isOptional(quantifiedType) ? "optional" : "accept";
			sbParser.append(String.format("reader.%s(%s);", acceptOrOptional, mapStringLiteral2TokenKind.get(key))).append(lineSeparator);
		} else {
			sbParser.append("parseLiteral(reader, registry);").append(lineSeparator);
		}
		return null;
	}

	public Void visit(QuantifiedExpression node, Object p) {
		switch (node.quantifierType()) {
			case "?":   visit(node.expression(), node.quantifierType());    break;
			case "*":
			case "+":
				buildQuantified(node.expression());
				break;
		}
		return null;
	}

	protected Identifier asIdentifier(Expression expr) {
		if (expr instanceof Identifier id)
			return id;
		if (expr instanceof QuantifiedExpression qe && qe.expression() instanceof Identifier id)
			return id;
		return null;
	}

	private void buildQuantified(Expression expr) {
		if (expr instanceof Identifier id) {
			if (StrUtils.isAllUpperCase(id.id())) {
				// ignore token kind.
			}
			boolean isDefinedRule = rules.containsKey(id.id());

			String variableName = id.id();
			String typeName = isDefinedRule
					? StringUtils.capitalize(variableName)
					: Identifier.class.getName().equalsIgnoreCase(variableName)
						? variableName
						: "Expression";

			String methodName = "parse" + typeName + "List";
			sbParser.append(indent2)
					.append(String.format("List<%s> %sList = %s", typeName, variableName, methodName))
					.append(ARGUMENTS_READER_REGISTRY).append(";").append(lineSeparator);
			sbParser.append(indent2).append(String.format("result.%sList(%sList);", variableName, variableName)).append(lineSeparator);

			buildParseListMethod(variableName, typeName, methodName);
		} else {
			System.out.println("buildQuantified does not support " + expr);
		}
	}

	private void buildParseListMethod(String variableName, String typeName, String methodName) {
		if (methods.containsKey(methodName))
			return ;

		StringBuilder sb = new StringBuilder();
		sb.append(String.format("public static List<%s> %s(TokenReader reader, ParserRegistry registry) {", typeName, methodName)).append(lineSeparator);
		sb.append(indent).append(String.format("List<%s> list = new ArrayList<>();", typeName)).append(lineSeparator);
		sb.append(indent).append("while (true) {").append(lineSeparator);
		sb.append(indent).append(indent).append(String.format("%s o = parse%s(reader, registry);", typeName, typeName)).append(lineSeparator);
		sb.append(indent).append(indent).append("if (o == null) break;").append(lineSeparator);
		sb.append(indent).append(indent).append("list.add(o);").append(lineSeparator);
		sb.append(indent).append("};").append(lineSeparator);
		sb.append(indent).append("return list;").append(lineSeparator);
		sb.append("}").append(lineSeparator);
		methods.put(methodName, sb.toString());
	}

	static final String HEADER = "package fc.compiler.language.cobol;\n" +
			"\n" +
			"import fc.compiler.common.ast.Expression;\n" +
			"import fc.compiler.common.ast.Statement;\n" +
			"import fc.compiler.common.ast.expression.*;\n" +
			"import fc.compiler.common.ast.statement.*;\n" +
			"import fc.compiler.common.parser.ParserBase;\n" +
			"import fc.compiler.common.parser.ParserRegistry;\n" +
			"import fc.compiler.common.parser.TokenReader;\n" +
			"import fc.compiler.common.token.Token;\n" +
			"import fc.compiler.language.cobol.ast.CharacterString;\n" +
			"import fc.compiler.language.cobol.ast.CobolCompilationUnit;\n" +
			"import fc.compiler.language.cobol.ast.CobolProgram;\n" +
			"import fc.compiler.language.cobol.ast.clause.*;\n" +
			"import fc.compiler.language.cobol.ast.division.*;\n" +
			"import fc.compiler.language.cobol.ast.expression.RoundedIdentifier;\n" +
			"import fc.compiler.language.cobol.ast.statement.*;\n" +
			"import lombok.extern.slf4j.Slf4j;\n" +
			"\n" +
			"import java.util.ArrayList;\n" +
			"import java.util.List;\n" +
			"\n" +
			"import static fc.compiler.common.token.TokenKind.*;\n" +
			"import static fc.compiler.language.cobol.CobolTokenKind.*;\n";
}
